version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      # mounting configuration and data directories from local filesystem to docker's container
      #      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
  mongodb:
    image: mongo
    container_name: mongodb-mqtt
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - springboot-mongodb_mongo-data:/data/db

volumes:
  springboot-mongodb_mongo-data:
    external: true