version: '3.8'

services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    user: root
    restart: always
    ports:
      - "1883:1883"
      - "8083:8083"
      - "18083:18083"
    environment:
      EMQX_LOADED_PLUGINS: "emqx_retainer, emqx_recon, emqx_dashboard, emqx_persistent"
      EMQX_ALLOW_ANONYMOUS: "true"
    volumes:
#      - C:/Users/Dao Huy Hung/IdeaProjects/mqtt/emqx/data:/opt/emqx/data
#      - C:/Users/Dao Huy Hung/IdeaProjects/mqtt/emqx/log:/opt/emqx/log
##      - ./emqx/etc/emqx.conf:/opt/emqx/etc/emqx.conf
#      - C:/Users/Dao Huy Hung/IdeaProjects/mqtt/emqx/etc/emqx.conf:/opt/emqx/etc/emqx.conf
      - ./emqx/etc/emqx.conf:/opt/emqx/etc/emqx.conf
      - ./emqx/data:/opt/emqx/data
      - ./emqx/log:/opt/emqx/log



  mongodb:
    image: mongo
    container_name: mongodb-mqtt
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - springboot-mongodb_mongo-data:/data/db

volumes:
  springboot-mongodb_mongo-data:
    external: true